services:
  - type: web
    name: tokyo-weekender-seo-dashboard
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_NODE_ENV
        value: production