services:
  - type: web
    name: tokyo-weekender-seo-dashboard
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_NODE_ENV
        value: production