"""Add competitor tables

Revision ID: 47d4d434520d
Revises: 
Create Date: 2025-09-26 07:43:53.933597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47d4d434520d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_competitor_sites_id', table_name='competitor_sites')
    op.drop_table('competitor_sites')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_sites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_keywords', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_traffic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_position', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='competitor_sites_pkey'),
    sa.UniqueConstraint('site_name', name='competitor_sites_site_name_key')
    )
    op.create_index('ix_competitor_sites_id', 'competitor_sites', ['id'], unique=False)
    # ### end Alembic commands ###
